FROM centos:7.9.2009

ENV KERL_REPO=https://github.com/kerl/kerl.git \
    KERL_TAG=2.5.1  \
    OTP_VERSION=R15B01

WORKDIR /tmp

RUN yum update -y \
&& yum install -y epel-release \
&& yum install -y https://packages.endpointdev.com/rhel/7/os/x86_64/endpoint-repo.x86_64.rpm \
&& yum install -y git curl curl-devel wget openssl telnet net-tools openssl-devel python3 libxslt fop java-1.8.0-openjdk wxGTK3\
&& yum install -y unixODBC-devel ncurses-devel gcc gcc-c++ zlib-devel expat-devel make automake autoconf \
&& git clone --branch ${KERL_TAG} ${KERL_REPO} \
&& cd kerl \
&& chmod a+x kerl \
&& mv kerl /usr/bin \
&& kerl update releases \
&& kerl build ${OTP_VERSION} ${OTP_VERSION} \
&& kerl install ${OTP_VERSION} /opt/erlang/${OTP_VERSION} \
&& echo ". /opt/erlang/${OTP_VERSION}/activate" >> /etc/bashrc \
&& export PATH=/opt/erlang/${OTP_VERSION}/bin:${PATH}

CMD ["/bin/bash"]